#!/usr/bin/env python3
"""Generate and validate Copilot adapters for canonical OpenCode sources."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_AGENT = Path(".opencode/agents/agent-team-designer.md")
COPILOT_AGENT = Path(".github/agents/agent-team-designer.agent.md")
SOURCE_MARKER = re.compile(
    r"<!-- Canonical OpenCode agent SHA-256: ([0-9a-f]{64}) -->"
)
CANONICAL_SKILLS = (
    "agent-audit",
    "agent-org-design",
    "model-selection",
    "prompt-patterns",
    "skill-security-audit",
)


def frontmatter(text: str, path: Path) -> str:
    match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        raise ValueError(f"{path} has no valid YAML frontmatter")
    return match.group(1)


def scalar(frontmatter_text: str, key: str) -> str:
    match = re.search(rf"^{re.escape(key)}:\s*(.+)$", frontmatter_text, re.MULTILINE)
    if not match:
        raise ValueError(f"missing {key!r} in skill frontmatter")
    return parse_string_scalar(match.group(1), key)


def adapter_for(name: str) -> str:
    canonical = Path(".opencode/skills") / name / "SKILL.md"
    source_frontmatter = frontmatter((ROOT / canonical).read_text(), canonical)
    source_name = scalar(source_frontmatter, "name")
    description = scalar(source_frontmatter, "description")
    if source_name != name:
        raise ValueError(f"{canonical} declares name {source_name!r}, expected {name!r}")

    runtime_note = ""
    if name == "model-selection":
        runtime_note = (
            " For Copilot CLI, model identifiers are bare values such as "
            "`gpt-5.6-terra`, not OpenCode's `github-copilot/<model-id>` form."
        )

    return (
        "---\n"
        f"name: {name}\n"
        f"description: {json.dumps(description, ensure_ascii=True)}\n"
        "---\n\n"
        f"# {name}\n\n"
        "<!-- Generated by scripts/sync_copilot_adapters.py; do not edit directly. -->\n\n"
        f"The canonical skill is `{canonical.as_posix()}`. Read that repository "
        "file and preserve its domain criteria, safety rules, and output intent. "
        "For a Copilot target, translate OpenCode-only fields and concepts to "
        "Copilot custom-agent schema and terminology: use `tools` and separate "
        "CLI approvals instead of OpenCode `permission`, omit OpenCode `mode`, "
        "`temperature`, `steps`, and `color`, and never imply these controls map "
        "one-for-one. If the canonical workflow requires an unavailable tool, "
        f"report `BLOCKED` rather than claiming validation.{runtime_note}\n"
    )


def expected_adapters() -> dict[Path, str]:
    return {
        Path(".github/skills") / name / "SKILL.md": adapter_for(name)
        for name in CANONICAL_SKILLS
    }


def normalized_digest(content: bytes) -> str:
    normalized = content.replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    return hashlib.sha256(normalized).hexdigest()


def source_agent_digest() -> str:
    return normalized_digest((ROOT / SOURCE_AGENT).read_bytes())


def symlink_in_path(relative_path: Path) -> Path | None:
    current = ROOT
    for part in relative_path.parts:
        current /= part
        if current.is_symlink():
            return current.relative_to(ROOT)
    return None


def require_safe_output_path(relative_path: Path) -> None:
    symlink = symlink_in_path(relative_path)
    if symlink is not None:
        raise ValueError(f"Copilot adapter path contains a symbolic link: {symlink}")


def generate_adapters() -> None:
    adapters = expected_adapters()
    for relative_path in adapters:
        require_safe_output_path(relative_path)
    for relative_path, content in adapters.items():
        path = ROOT / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"generated {relative_path}")


def accept_agent_source() -> None:
    require_safe_output_path(COPILOT_AGENT)
    path = ROOT / COPILOT_AGENT
    text = path.read_text()
    replacement = f"<!-- Canonical OpenCode agent SHA-256: {source_agent_digest()} -->"
    if not SOURCE_MARKER.search(text):
        raise ValueError(f"{COPILOT_AGENT} has no canonical source marker")
    path.write_text(SOURCE_MARKER.sub(replacement, text, count=1))
    print(f"accepted {SOURCE_AGENT} for {COPILOT_AGENT}")


def parse_agent_frontmatter(text: str) -> dict[str, object]:
    data: dict[str, object] = {}
    current_list: list[str] | None = None
    current_key: str | None = None
    for line in frontmatter(text, COPILOT_AGENT).splitlines():
        if line.startswith("  - ") and current_list is not None:
            current_list.append(line[4:].strip())
            continue
        match = re.match(r"^([a-z-]+):(?:\s*(.*))?$", line)
        if not match:
            raise ValueError(f"unsupported Copilot frontmatter syntax: {line!r}")
        key, value = match.groups()
        if key in data:
            raise ValueError(f"duplicate Copilot frontmatter key: {key}")
        if value:
            data[key] = parse_string_scalar(value, key)
            current_list = None
            current_key = key
        else:
            current_list = []
            data[key] = current_list
            current_key = key
    if current_list is not None and not current_list:
        raise ValueError(f"Copilot frontmatter list is empty: {current_key}")
    return data


def parse_string_scalar(value: str, key: str) -> str:
    value = value.strip()
    if value.startswith('"'):
        if not value.endswith('"'):
            raise ValueError(f"Copilot frontmatter {key} must be a string")
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError as error:
            raise ValueError(
                f"Copilot frontmatter {key} must be a string"
            ) from error
        if isinstance(parsed, str):
            return parsed
    elif value.startswith("'"):
        valid_content = re.fullmatch(r"(?:[^']|'')*", value[1:-1])
        if not value.endswith("'") or not valid_content:
            raise ValueError(f"Copilot frontmatter {key} must be a string")
        return value[1:-1].replace("''", "'")
    elif not re.fullmatch(
        r"(?i:null|~|true|false|yes|no|on|off|[-+]?(?:\d+(?:\.\d*)?|\.\d+))",
        value,
    ) and not value.startswith(
        ("[", "{", "|", ">", "&", "*", "!", "#", "@", "`", "'", '"')
    ) and not re.search(r":\s|\s#", value):
        return value
    raise ValueError(f"Copilot frontmatter {key} must be a string")


def validate_agent_metadata(copilot: dict[str, object]) -> list[str]:
    errors: list[str] = []
    if set(copilot) != {"name", "description", "model", "tools"}:
        errors.append("Copilot agent frontmatter has unexpected or missing keys")
    if copilot.get("name") != "agent-team-designer":
        errors.append("Copilot agent name must be agent-team-designer")
    description = copilot.get("description")
    if not isinstance(description, str) or not description.strip():
        errors.append("Copilot agent description must be a non-empty string")
    if copilot.get("tools") != ["read", "search", "web"]:
        errors.append("Copilot agent must expose only read, search, and web")
    model = copilot.get("model")
    if not isinstance(model, str) or not model or "/" in model:
        errors.append("Copilot agent model must be a bare CLI identifier")
    return errors


def validate() -> list[str]:
    errors: list[str] = []
    adapters = expected_adapters()
    unsafe_paths: set[Path] = set()

    for relative_path in (*adapters.keys(), COPILOT_AGENT):
        symlink = symlink_in_path(relative_path)
        if symlink is not None:
            errors.append(
                f"Copilot adapter path contains a symbolic link: {symlink}"
            )
            unsafe_paths.add(relative_path)

    for relative_path, expected in adapters.items():
        if relative_path in unsafe_paths:
            continue
        path = ROOT / relative_path
        if not path.exists():
            errors.append(f"missing generated adapter: {relative_path}")
        elif path.read_text() != expected:
            errors.append(
                f"stale generated adapter: {relative_path}; run "
                "python3 scripts/sync_copilot_adapters.py"
            )

    if COPILOT_AGENT not in unsafe_paths:
        copilot_path = ROOT / COPILOT_AGENT
        copilot_text = copilot_path.read_text()
        marker = SOURCE_MARKER.search(copilot_text)
        if not marker or marker.group(1) != source_agent_digest():
            errors.append(
                f"{SOURCE_AGENT} changed; adapt {COPILOT_AGENT}, then run "
                "python3 scripts/sync_copilot_adapters.py --accept-agent-source"
            )

        try:
            copilot = parse_agent_frontmatter(copilot_text)
        except ValueError as error:
            errors.append(str(error))
            copilot = {}
        errors.extend(validate_agent_metadata(copilot))
        if len(copilot_text) >= 30_000:
            errors.append("Copilot agent profile exceeds the 30,000-character limit")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate adapters without writing files",
    )
    parser.add_argument(
        "--accept-agent-source",
        action="store_true",
        help="record that the Copilot translation was reviewed against the current OpenCode agent",
    )
    args = parser.parse_args()

    try:
        if args.accept_agent_source:
            accept_agent_source()
        elif not args.check:
            generate_adapters()
        errors = validate()
    except (OSError, ValueError) as error:
        errors = [str(error)]

    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1
    print("Copilot adapters match their canonical OpenCode sources")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
