#!/usr/bin/env python3
"""Generate Copilot skill adapters and validate cross-runtime invariants."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SHARED_BEHAVIOR = Path("docs/agent-team-designer-behavior.md")
CANONICAL_SKILLS = (
    "agent-audit",
    "agent-org-design",
    "model-selection",
    "prompt-patterns",
    "skill-security-audit",
)
FINAL_STATUSES = ("COMPLETE", "PARTIAL", "BLOCKED", "UNSAFE TO CONTINUE")


def frontmatter(text: str, path: Path) -> str:
    match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        raise ValueError(f"{path} has no valid YAML frontmatter")
    return match.group(1)


def scalar(frontmatter_text: str, key: str) -> str:
    match = re.search(rf"^{re.escape(key)}:\s*(.+)$", frontmatter_text, re.MULTILINE)
    if not match:
        raise ValueError(f"missing {key!r} in skill frontmatter")
    return match.group(1).strip().strip('"\'')


def adapter_for(name: str) -> str:
    canonical = Path(".opencode/skills") / name / "SKILL.md"
    source = ROOT / canonical
    source_frontmatter = frontmatter(source.read_text(), canonical)
    source_name = scalar(source_frontmatter, "name")
    description = scalar(source_frontmatter, "description")
    if source_name != name:
        raise ValueError(f"{canonical} declares name {source_name!r}, expected {name!r}")

    runtime_note = ""
    if name == "model-selection":
        runtime_note = (
            " When the target is Copilot CLI, translate OpenCode's "
            "`github-copilot/<model-id>` values to the bare `<model-id>` "
            "accepted by Copilot CLI."
        )

    return (
        "---\n"
        f"name: {name}\n"
        f"description: {json.dumps(description, ensure_ascii=True)}\n"
        "---\n\n"
        f"# {name}\n\n"
        "<!-- Generated by scripts/sync_runtime_docs.py; do not edit directly. -->\n\n"
        f"The canonical skill is `{canonical.as_posix()}`. Read that repository "
        "file and follow its complete workflow. This adapter exists only for "
        f"Copilot CLI repository discovery.{runtime_note}\n"
    )


def expected_adapters() -> dict[Path, str]:
    return {
        Path(".github/skills") / name / "SKILL.md": adapter_for(name)
        for name in CANONICAL_SKILLS
    }


def generate() -> None:
    for relative_path, content in expected_adapters().items():
        path = ROOT / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"generated {relative_path}")


def parse_simple_agent_frontmatter(text: str, path: Path) -> dict[str, object]:
    data: dict[str, object] = {}
    current_list: list[str] | None = None
    for line in frontmatter(text, path).splitlines():
        if line.startswith("  - ") and current_list is not None:
            current_list.append(line[4:].strip())
            continue
        match = re.match(r"^([a-z-]+):(?:\s*(.*))?$", line)
        if not match:
            continue
        key, value = match.groups()
        if value:
            data[key] = value.strip().strip('"\'')
            current_list = None
        else:
            current_list = []
            data[key] = current_list
    return data


def validate() -> list[str]:
    errors: list[str] = []

    for relative_path, expected in expected_adapters().items():
        path = ROOT / relative_path
        if not path.exists():
            errors.append(f"missing generated adapter: {relative_path}")
        elif path.read_text() != expected:
            errors.append(
                f"stale generated adapter: {relative_path}; run "
                "python3 scripts/sync_runtime_docs.py"
            )

    shared_path = ROOT / SHARED_BEHAVIOR
    shared = shared_path.read_text() if shared_path.exists() else ""
    normalized_shared = " ".join(shared.lower().split())
    if not shared:
        errors.append(f"missing canonical behavior: {SHARED_BEHAVIOR}")
    for status in FINAL_STATUSES:
        if status not in shared:
            errors.append(f"canonical behavior is missing final status {status}")
    for phrase in (
        "least privilege",
        "destination path",
        "global installations",
        "symbolic links",
        "session databases",
        "at most twice",
        "validation without naming",
    ):
        if phrase.lower() not in normalized_shared:
            errors.append(f"canonical behavior is missing invariant: {phrase}")

    reference = SHARED_BEHAVIOR.as_posix()
    consumers = (
        Path("AGENTS.md"),
        Path(".github/copilot-instructions.md"),
        Path(".github/agents/agent-team-designer.agent.md"),
        Path(".opencode/agents/agent-team-designer.md"),
    )
    for relative_path in consumers:
        path = ROOT / relative_path
        if not path.exists() or reference not in path.read_text():
            errors.append(f"{relative_path} must reference {reference}")

    copilot_path = Path(".github/agents/agent-team-designer.agent.md")
    copilot_text = (ROOT / copilot_path).read_text()
    try:
        copilot = parse_simple_agent_frontmatter(copilot_text, copilot_path)
    except ValueError as error:
        errors.append(str(error))
        copilot = {}
    expected_keys = {"name", "description", "model", "tools"}
    if set(copilot) != expected_keys:
        errors.append("Copilot agent frontmatter has unexpected or missing keys")
    if copilot.get("tools") != ["read", "search", "web"]:
        errors.append("Copilot agent must expose only read, search, and web")
    model = copilot.get("model", "")
    if not isinstance(model, str) or not model or "/" in model:
        errors.append("Copilot agent model must be a bare CLI identifier")
    if len(copilot_text) >= 30_000:
        errors.append("Copilot agent profile exceeds the 30,000-character limit")

    try:
        config = json.loads((ROOT / "opencode.json").read_text())
    except (OSError, json.JSONDecodeError) as error:
        errors.append(f"invalid opencode.json: {error}")
        config = {}
    instructions = config.get("instructions", [])
    if "AGENTS.md" not in instructions or reference not in instructions:
        errors.append("opencode.json must load AGENTS.md and canonical behavior")
    if config.get("skills", {}).get("paths") != [".opencode/skills"]:
        errors.append("opencode.json must retain .opencode/skills as its skill source")
    if config.get("default_agent") != "agent-team-designer":
        errors.append("opencode.json must retain agent-team-designer as default")

    opencode_path = Path(".opencode/agents/agent-team-designer.md")
    opencode_agent = (ROOT / opencode_path).read_text()
    opencode_frontmatter = frontmatter(opencode_agent, opencode_path)
    for required in ("model: github-copilot/", "steps: 40"):
        if required not in opencode_frontmatter:
            errors.append(f"OpenCode agent is missing runtime invariant: {required}")

    permission_match = re.search(
        r"^permission:\n(?P<rules>(?:  [^\n]+\n?)+)$",
        opencode_frontmatter,
        re.MULTILINE,
    )
    permission_rules = permission_match.group("rules").rstrip() if permission_match else ""
    expected_permission_rules = "\n".join(
        (
            "  edit: ask",
            "  bash:",
            '    "*": deny',
            '    "git status*": allow',
            '    "git diff*": allow',
            '    "git log*": allow',
            '    "mkdir *": allow',
            '    "New-Item -ItemType Directory*": allow',
            "  task:",
            '    "*": deny',
            "  skill: allow",
        )
    )
    if permission_rules != expected_permission_rules:
        errors.append(
            "OpenCode permissions changed; retain the approved ordered permission "
            "block or update this invariant with an explicit review"
        )

    protected_paths = (
        SHARED_BEHAVIOR,
        Path("AGENTS.md"),
        Path("opencode.json"),
        Path(".github/copilot-instructions.md"),
        copilot_path,
        Path(".opencode/agents/agent-team-designer.md"),
        *expected_adapters().keys(),
    )
    for relative_path in protected_paths:
        if (ROOT / relative_path).is_symlink():
            errors.append(f"runtime configuration must not be a symbolic link: {relative_path}")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate generated adapters and cross-runtime invariants without writing",
    )
    args = parser.parse_args()

    if not args.check:
        generate()

    try:
        errors = validate()
    except (OSError, ValueError) as error:
        errors = [str(error)]
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1
    print("runtime documentation and configuration are synchronized")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
